#!/usr/bin/env node
/**
 * Turns the brand pack (brand/*.svg, B1 monogram + custom-drawn v2 wordmark, brand/README.md) into what the site uses.
 *
 *   node scripts/build-brand.mjs          write the files
 *   node scripts/build-brand.mjs --check  write nothing, fail if a generated file is out of date (the audit runs this)
 *
 * Generated, never edited by hand:
 *   lib/brand-paths.ts            the outlines of the logo parts as strings, read by components/ui/Logo.tsx
 *   app/icon.svg                  the browser-tab icon (brand/favicon.svg, byte for byte)
 *   app/apple-icon.png            180 x 180, full-bleed obsidian square (iOS rounds the corners itself)
 *   public/brand/logo-512.png     512 x 512, the same square, for structured data (search engines want a raster logo)
 *
 * The logo is one colour (platin on dark, obsidian on light), never a gradient, shadow or glow, and is drawn from curves, not
 * set in a live font (brand/README.md). The site paints it with `currentColor`, which is platin where it appears.
 */
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');
const read = (rel) => readFileSync(join(root, rel), 'utf8');

const PARTS = {
  monogram: 'brand/monogram-b1-platin.svg',
  monogramSmall: 'brand/monogram-b1-small-platin.svg',
  lockupHorizontal: 'brand/lockup-horizontal-platin.svg',
  lockupStacked: 'brand/lockup-stacked-platin.svg',
  wordmark: 'brand/wordmark-platin.svg',
};

const attr = (svg, name, file) => {
  const match = svg.match(new RegExp(`${name}="([^"]+)"`));
  if (!match) throw new Error(`${file}: no ${name} attribute`);
  return match[1];
};

let body = '';
for (const [key, file] of Object.entries(PARTS)) {
  const svg = read(file);
  const viewBox = attr(svg, 'viewBox', file);
  const [, , w, h] = viewBox.split(' ').map(Number);
  body += `  ${key}: { viewBox: '${viewBox}', w: ${w}, h: ${h}, d: '${attr(svg, ' d', file)}' },\n`;
}
const paths = `// Generated by scripts/build-brand.mjs from brand/*.svg. Do not edit; edit the SVG and run \`npm run brand:build\`.
export const BRAND = {
${body}} as const;

export type BrandPart = keyof typeof BRAND;
export const BRAND_COLORS = { platin: '#E2E2E6', obsidian: '#0D0D0E' } as const;
`;

// A full-bleed square for platforms that round the corners themselves: the favicon's monogram path on an obsidian square.
const favicon = read('brand/favicon.svg');
const mark = attr(favicon, ' d', 'brand/favicon.svg');
const square = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><rect width="32" height="32" fill="${'#0D0D0E'}"/><path fill-rule="evenodd" fill="${'#E2E2E6'}" d="${mark}"/></svg>`;

const outputs = [
  ['lib/brand-paths.ts', Buffer.from(paths)],
  ['app/icon.svg', Buffer.from(favicon)],
  ['app/apple-icon.png', await sharp(Buffer.from(square), { density: 576 }).resize(180, 180).png({ compressionLevel: 9 }).toBuffer()],
  ['public/brand/logo-512.png', await sharp(Buffer.from(square), { density: 1536 }).resize(512, 512).png({ compressionLevel: 9 }).toBuffer()],
];

let stale = 0;
for (const [rel, data] of outputs) {
  const target = join(root, rel);
  const same = existsSync(target) && readFileSync(target).equals(data);
  if (check) {
    if (!same) {
      stale += 1;
      console.log(`STALE  ${rel}`);
    }
    continue;
  }
  mkdirSync(dirname(target), { recursive: true });
  if (!same) writeFileSync(target, data);
  console.log(`${same ? 'same ' : 'write'}  ${rel}  ${data.length} bytes`);
}
if (check) {
  console.log(stale ? `${stale} generated brand file(s) are out of date: run npm run brand:build` : 'brand files are up to date');
  process.exit(stale ? 1 : 0);
}
